export type { ContentSource } from './plugin/ContentSource'

export { default as ContentBlock } from './components/ContentBlock.vue'
export { useContent } from './composables/useContent'
export { VueContent } from './plugin/VueContent'
export type { Block } from './plugin/Block'
export { InMemorySource } from './plugin/InMemorySource'
export { LocalizedInMemorySource } from './plugin/LocalizedInMemorySource'
export { replaceVariables } from './utils/replaceVariables'
export { sanitize } from './utils/sanitize'
